In [ ]:
"""Q1. What is a database? Differentiate between SQL and NoSQL databases."""
Ans.
    A database is an organized collection of structured information, or data,
    typically stored electronically in a computer system. A database is usually 
    controlled by a database management system (DBMS).
    
SQL:
    i. RELATIONAL DATABASE MANAGEMENT SYSTEM (RDBMS).
    ii. These databases have fixed or static or predefined schema.
    iii. These databases are not suited for hierarchical data storage.
    iv. These databases are best suited for complex queries.
    v. Vertically Scalable.
    
NoSQL:
    i. Non-relational or distributed database system.
    ii. They have a dynamic schema.
    iii. These databases are best suited for hierarchical data storage.
    iv. These databases are not so good for complex queries.
    v. Horizontally scalable.

In [ ]:
"""Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an exampample"""

Ans.
   Data Definition Language (DDL) is a subset of SQL.
    It is a language for describing data and its relationships in a database.
    DDL describes the portion of SQL that creates, alters, and deletes database objects.
    
CREATE : The CREATE TABLE command creates a new table in the database.
e.g: CREATE TABLE Student(Roll INT,Name VARCHAR(20),Marks FLOAT);

DROP : The DROP TABLE command deletes a table in the database.
e.g: DROP TABLE Student;

ALTER: The ALTER TABLE command adds, deletes, or modifies columns in a table.
e.g: ALTER TABLE Student ADD Email VARCHAR(30);
    ALTER TABLE Student DROP COULMN Email;
    
TRUNCATE: The TRUNCATE TABLE command deletes the data inside a table, but not the table itself.
e.g: TRUNCATE TABLE Student;

In [ ]:
"""Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example?"""

Ans.
    DML is an abbreviation of Data Manipulation Language.
    The DML in DBMS is responsible for performing CRUD 
    (Create Read Update and Delete) operations on the data of the database table.
    DML commands are INSERT, UPDATE, and DELETE.
    
INSERT : INSERT is data manipulation command in Structured Query Language,
          which allows users to insert data in database tables.
e.g: INSERT INTO Student (Stu_id, Stu_Name, Stu_Marks, Stu_Age) VALUES (435, Trimal, 93, 19);
     INSERT INTO Student (Stu_id, Stu_Name, Stu_Marks, Stu_Age) VALUES (135, Nag, 65, 19);

UPDATE : UPDATE is data manipulation command in Structured Query Language,
          which allows users to update or modify the existing data in database tables.
e.g: UPDATE Sstudent SET Stu_marks = 95 WHERE Stu_id = 435 ;  

DELETE : DELETE is a DML command which allows SQL users to remove 
          single or multiple existing records from the database tables.
e.g: DELETE FROM Student WHERE Stu_Marks > 70 ;

In [ ]:
"""Q4. What is DQL? Explain SELECT with an example?"""

Ans.
    Data Query Languages, are computer languages that are used to make various
    queries in information systems and databases. The Structured Query Language (SQL) is a 
    well-known example. DQL statements are used to query the data contained in schema objects.
    
e.g: SELECT * FROM Name_of_Table WHERE [condition];
     SELECT * FROM Student WHERE Stu_Age > 18;

In [ ]:
"""Q5. Explain Primary Key and Foreign Key?"""

Ans.
PRIMARY KEY : It is used to identify each record into the database table uniquely.
              The primary key column value can never be NULL.
              A table can have only one primary key.
              The primary key is a unique attribute, it cannot stores duplicate values in relation.
              It cannot create a parent-child relationship in a table.

FORIGN KEY:  It is used to links two tables together. 
             It means the foreign key in one table refers to the primary key of another table.
             The foreign key column can accept a NULL value.
             A table can have more than one foreign key.
             We can store duplicate values in the foreign key column.
             It can make a parent-child relationship in a table.

In [ ]:
"""Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method?"""

Ans.

import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
)
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")
for x in mycursor:
    print(x)
    
cursor(): The cursor object can be defined as an abstraction specified in the Python DB-API 2.0.
           It facilitates us to have multiple separate working environments through the same
           connection to the database. We can create the cursor object by calling the 'cursor' 
           function of the connection object. The cursor object is an important aspect of 
            executing queries to the databases.
            
execute(): The Execute method executes a specified query, SQL statement, stored procedure, 
            or provider-specific text. The results are stored in a new Recordset object 
            if it is a row-returning query. A closed Recordset object will be returned 
            if it is not a row-returning query.

In [ ]:
"""Q7. Give the order of execution of SQL clauses in an SQL query?"""

Ans.
FROM clause: Specifies the table or tables from which the data is retrieved.

WHERE clause: Filters the rows based on specific conditions.

GROUP BY clause: Groups the rows based on one or more columns.

HAVING clause: Filters the groups based on specific conditions.

SELECT clause: Specifies the columns to be included in the result set.

ORDER BY clause: Sorts the result set based on one or more columns.

LIMIT/OFFSET clause: Limits the number of rows returned or skips a specified number of rows..